In [1]:
import pandas as pd

# Scraping with Pandas

We can use the `read_html` function in Pandas to automatically scrape any tabular data from a page.

In [2]:
url = 'https://animalcrossing.fandom.com/wiki/Fish_(New_Horizons)'

In [3]:
# Reading url table into a df
tables = pd.read_html(url)
tables[2]

,Name,Image,Price,Location,Shadow size,Time,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,Bitterling,NaN,900,River,1,All day,✓,✓,✓,-,-,-,-,-,-,-,✓,✓
1,Pale chub,NaN,200,River,1,9 AM - 4 PM,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓
2,Crucian carp,NaN,160,River,2,All day,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓
3,Dace,NaN,240,River,3,4 PM - 9 AM,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓
4,Carp,NaN,300,Pond,4,All day,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Suckerfish,NaN,1500,Sea,4 (Fin),All day,-,-,-,-,-,✓,✓,✓,✓,-,-,-
76,Football fish,NaN,2500,Sea,4,4 PM - 9 AM,✓,✓,✓,-,-,-,-,-,-,-,✓,✓
77,Oarfish,NaN,9000,Sea,6,All day,✓,✓,✓,✓,✓,-,-,-,-,-,-,✓
78,Barreleye,NaN,15000,Sea,2,9 PM - 4 AM,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓
79,Coelacanth,NaN,15000,Sea (Raining),6,All day,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓

# Data Transformation

In [4]:
# storing the third table from the url in a df
df = tables[2]
# deleting the image column
del df["Image"]
# displaying the df
df

,Name,Price,Location,Shadow size,Time,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,Bitterling,900,River,1,All day,✓,✓,✓,-,-,-,-,-,-,-,✓,✓
1,Pale chub,200,River,1,9 AM - 4 PM,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓
2,Crucian carp,160,River,2,All day,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓
3,Dace,240,River,3,4 PM - 9 AM,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓
4,Carp,300,Pond,4,All day,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Suckerfish,1500,Sea,4 (Fin),All day,-,-,-,-,-,✓,✓,✓,✓,-,-,-
76,Football fish,2500,Sea,4,4 PM - 9 AM,✓,✓,✓,-,-,-,-,-,-,-,✓,✓
77,Oarfish,9000,Sea,6,All day,✓,✓,✓,✓,✓,-,-,-,-,-,-,✓
78,Barreleye,15000,Sea,2,9 PM - 4 AM,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓
79,Coelacanth,15000,Sea (Raining),6,All day,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓,✓

In [5]:
# Replacing check marks with True and minus signs with False
df["Jan"] = df["Jan"].replace("✓", True).replace("-", False)
df["Feb"] = df["Feb"].replace("✓", True).replace("-", False)
df["Mar"] = df["Mar"].replace("✓", True).replace("-", False)
df["Apr"] = df["Apr"].replace("✓", True).replace("-", False)
df["May"] = df["May"].replace("✓", True).replace("-", False)
df["Jun"] = df["Jun"].replace("✓", True).replace("-", False)
df["Jul"] = df["Jul"].replace("✓", True).replace("-", False)
df["Aug"] = df["Aug"].replace("✓", True).replace("-", False)
df["Sep"] = df["Sep"].replace("✓", True).replace("-", False)
df["Oct"] = df["Oct"].replace("✓", True).replace("-", False)
df["Nov"] = df["Nov"].replace("✓", True).replace("-", False)
df["Dec"] = df["Dec"].replace("✓", True).replace("-", False)
    
# Capitalizing the name column
df["Name"] = df["Name"].str.title()

# Displaying df
df

,Name,Price,Location,Shadow size,Time,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,Bitterling,900,River,1,All day,True,True,True,False,False,False,False,False,False,False,True,True
1,Pale Chub,200,River,1,9 AM - 4 PM,True,True,True,True,True,True,True,True,True,True,True,True
2,Crucian Carp,160,River,2,All day,True,True,True,True,True,True,True,True,True,True,True,True
3,Dace,240,River,3,4 PM - 9 AM,True,True,True,True,True,True,True,True,True,True,True,True
4,Carp,300,Pond,4,All day,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Suckerfish,1500,Sea,4 (Fin),All day,False,False,False,False,False,True,True,True,True,False,False,False
76,Football Fish,2500,Sea,4,4 PM - 9 AM,True,True,True,False,False,False,False,False,False,False,True,True
77,Oarfish,9000,Sea,6,All day,True,True,True,True,True,False,False,False,False,False,False,True
78,Barreleye,15000,Sea,2,9 PM - 4 AM,True,True,True,True,True,True,True,True,True,True,True,True
79,Coelacanth,15000,Sea (Raining),6,All day,True,True,True,True,True,True,True,True,True,True,True,True

## Fish ID df

In [6]:
# Reading id csv 
filepath = "ids.csv"

# Reading csv into a df
id_df = pd.read_csv(filepath)

# Filtering id df to only contain Fish 
fish_id = id_df.loc[id_df['Type']=='Fish']

## Merging ID and fish df

In [7]:
# Merging fish id and fish df
fish_id_merge = df.merge(fish_id[["ID","Name"]],on='Name',how='left')

# Setting the index to ID
fish_id_merge = fish_id_merge.set_index("ID")

# Displaying the df
fish_id_merge

,Name,Price,Location,Shadow size,Time,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
ID,,,,,,,,,,,,,,,,,
F01,Bitterling,900,River,1,All day,True,True,True,False,False,False,False,False,False,False,True,True
F02,Pale Chub,200,River,1,9 AM - 4 PM,True,True,True,True,True,True,True,True,True,True,True,True
F03,Crucian Carp,160,River,2,All day,True,True,True,True,True,True,True,True,True,True,True,True
F04,Dace,240,River,3,4 PM - 9 AM,True,True,True,True,True,True,True,True,True,True,True,True
F05,Carp,300,Pond,4,All day,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F76,Suckerfish,1500,Sea,4 (Fin),All day,False,False,False,False,False,True,True,True,True,False,False,False
F77,Football Fish,2500,Sea,4,4 PM - 9 AM,True,True,True,False,False,False,False,False,False,False,True,True
F78,Oarfish,9000,Sea,6,All day,True,True,True,True,True,False,False,False,False,False,False,True
F79,Barreleye,15000,Sea,2,9 PM - 4 AM,True,True,True,True,True,True,True,True,True,True,True,True
F80,Coelacanth,15000,Sea (Raining),6,All day,True,True,True,True,True,True,True,True,True,True,True,True

## Splitting dataframe

In [15]:
# Creating a df for the fish 
fish_df = fish_id_merge.iloc[:,:4]

# Displaying the fish df
fish_df

              Name  Price       Location Shadow size
ID
F01     Bitterling    900          River           1
F02      Pale Chub    200          River           1
F03   Crucian Carp    160          River           2
F04           Dace    240          River           3
F05           Carp    300           Pond           4
..             ...    ...            ...         ...
F76     Suckerfish   1500            Sea     4 (Fin)
F77  Football Fish   2500            Sea           4
F78        Oarfish   9000            Sea           6
F79      Barreleye  15000            Sea           2
F80     Coelacanth  15000  Sea (Raining)           6

[80 rows x 4 columns]

In [9]:
# Creating a df for the months fish are available
fish_months_df = fish_id_merge.iloc[:,5:]

# Displaying fish months df
fish_months_df

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
ID,,,,,,,,,,,,
F01,True,True,True,False,False,False,False,False,False,False,True,True
F02,True,True,True,True,True,True,True,True,True,True,True,True
F03,True,True,True,True,True,True,True,True,True,True,True,True
F04,True,True,True,True,True,True,True,True,True,True,True,True
F05,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
F76,False,False,False,False,False,True,True,True,True,False,False,False
F77,True,True,True,False,False,False,False,False,False,False,True,True
F78,True,True,True,True,True,False,False,False,False,False,False,True
F79,True,True,True,True,True,True,True,True,True,True,True,True
F80,True,True,True,True,True,True,True,True,True,True,True,True

In [14]:
# Creating a df for the months fish are available
fish_time_df = fish_id_merge.iloc[:,4:5]

# Displaying fish months df
fish_time_df

            Time
ID
F01      All day
F02  9 AM - 4 PM
F03      All day
F04  4 PM - 9 AM
F05      All day
..           ...
F76      All day
F77  4 PM - 9 AM
F78      All day
F79  9 PM - 4 AM
F80      All day

[80 rows x 1 columns]

## DataFrames as HTML

Pandas also had a `to_html` method that we can use to generate HTML tables from DataFrames.

In [10]:
html_table = df.to_html()
html_table

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Name</th>\n      <th>Price</th>\n      <th>Location</th>\n      <th>Shadow size</th>\n      <th>Time</th>\n      <th>Jan</th>\n      <th>Feb</th>\n      <th>Mar</th>\n      <th>Apr</th>\n      <th>May</th>\n      <th>Jun</th>\n      <th>Jul</th>\n      <th>Aug</th>\n      <th>Sep</th>\n      <th>Oct</th>\n      <th>Nov</th>\n      <th>Dec</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Bitterling</td>\n      <td>900</td>\n      <td>River</td>\n      <td>1</td>\n      <td>All day</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Pale Chub</td>\n      <td>200</td>\n      <td>River</td>\n      <td>1</td>\n      <td>9 AM - 4 PM</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Crucian Carp</td>\n      <td>160</td>\n      <td>River</td>\n      <td>2</td>\n      <td>All day</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Dace</td>\n      <td>240</td>\n      <td>River</td>\n      <td>3</td>\n      <td>4 PM - 9 AM</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Carp</td>\n      <td>300</td>\n      <td>Pond</td>\n      <td>4</td>\n      <td>All day</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Koi</td>\n      <td>4000</td>\n      <td>Pond</td>\n      <td>4</td>\n      <td>4 PM - 9 AM</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Goldfish</td>\n      <td>1300</td>\n      <td>Pond</td>\n      <td>1</td>\n      <td>All day</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Pop-Eyed Goldfish</td>\n      <td>1300</td>\n      <td>Pond</td>\n      <td>1</td>\n      <td>9 AM - 4 PM</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Ranchu Goldfish</td>\n      <td>4500</td>\n      <td>Pond</td>\n      <td>2</td>\n      <td>9 AM - 4 PM</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Killifish</td>\n      <td>300</td>\n      <td>Pond</td>\n      <td>1</td>\n      <td>All day</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Crawfish</td>\n      <td>200</td>\n      <td>Pond</td>\n      <td>2</td>\n      <td>All day</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Soft-Shelled Turtle</td>\n      <td>3750</td>\n      <td>River</td>\n      <td>4</td>\n      <td>4 PM - 9 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Snapping Turtle</td>\n      <td>5000</td>\n      <td>River</td>\n      <td>5</td>\n      <td>9 PM - 4 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Tadpole</td>\n      <td>100</td>\n      <td>Pond</td>\n      <td>1</td>\n      <td>All day</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Frog</td>\n      <td>120</td>\n      <td>Pond</td>\n      <td>2</td>\n      <td>All day</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>Freshwater Goby</td>\n      <td>400</td>\n      <td>River</td>\n      <td>2</td>\n      <td>4 PM - 9 AM</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>Loach</td>\n      <td>400</td>\n      <td>River</td>\n      <td>2</td>\n      <td>All day</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>Catfish</td>\n      <td>800</td>\n      <td>Pond</td>\n      <td>4</td>\n      <td>4 PM - 9 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>Giant Snakehead</td>\n      <td>5500</td>\n      <td>Pond</td>\n      <td>5</td>\n      <td>9 AM - 4 PM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>Bluegill</td>\n      <td>180</td>\n      <td>River</td>\n      <td>2</td>\n      <td>9 AM - 4 PM</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>Yellow Perch</td>\n      <td>300</td>\n      <td>River</td>\n      <td>3</td>\n      <td>All day</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>Black Bass</td>\n      <td>400</td>\n      <td>River</td>\n      <td>4</td>\n      <td>All day</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>Tilapia</td>\n      <td>800</td>\n      <td>River</td>\n      <td>3</td>\n      <td>All day</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>Pike</td>\n      <td>1800</td>\n      <td>River</td>\n      <td>5</td>\n      <td>All day</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>24</th>\n      <td>Pond Smelt</td>\n      <td>500</td>\n      <td>River</td>\n      <td>2</td>\n      <td>All day</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>25</th>\n      <td>Sweetfish</td>\n      <td>900</td>\n      <td>River</td>\n      <td>3</td>\n      <td>All day</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>26</th>\n      <td>Cherry Salmon</td>\n      <td>1000</td>\n      <td>River (Clifftop)</td>\n      <td>3</td>\n      <td>4 PM - 9 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>27</th>\n      <td>Char</td>\n      <td>3800</td>\n      <td>River (Clifftop) Pond</td>\n      <td>3</td>\n      <td>4 PM - 9 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>28</th>\n      <td>Golden Trout</td>\n      <td>15000</td>\n      <td>River (Clifftop)</td>\n      <td>3</td>\n      <td>4 PM - 9 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>29</th>\n      <td>Stringfish</td>\n      <td>15000</td>\n      <td>River (Clifftop)</td>\n      <td>5</td>\n      <td>4 PM - 9 AM</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>30</th>\n      <td>Salmon</td>\n      <td>700</td>\n      <td>River (Mouth)</td>\n      <td>4</td>\n      <td>All day</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>31</th>\n      <td>King Salmon</td>\n      <td>1800</td>\n      <td>River (Mouth)</td>\n      <td>6</td>\n      <td>All day</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>32</th>\n      <td>Mitten Crab</td>\n      <td>2000</td>\n      <td>River</td>\n      <td>2</td>\n      <td>4 PM - 9 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>33</th>\n      <td>Guppy</td>\n      <td>1300</td>\n      <td>River</td>\n      <td>1</td>\n      <td>9 AM - 4 PM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>34</th>\n      <td>Nibble Fish</td>\n      <td>1500</td>\n      <td>River</td>\n      <td>1</td>\n      <td>9 AM - 4 PM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>35</th>\n      <td>Angelfish</td>\n      <td>3000</td>\n      <td>River</td>\n      <td>2</td>\n      <td>4 PM - 9 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>36</th>\n      <td>Betta</td>\n      <td>2500</td>\n      <td>River</td>\n      <td>2</td>\n      <td>9 AM - 4 PM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>37</th>\n      <td>Neon Tetra</td>\n      <td>500</td>\n      <td>River</td>\n      <td>1</td>\n      <td>9 AM - 4 PM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>38</th>\n      <td>Rainbowfish</td>\n      <td>800</td>\n      <td>River</td>\n      <td>1</td>\n      <td>9 AM - 4 PM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>39</th>\n      <td>Piranha</td>\n      <td>2500</td>\n      <td>River</td>\n      <td>2</td>\n      <td>9 AM - 4 PM &amp; 9 PM - 4 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>40</th>\n      <td>Arowana</td>\n      <td>10000</td>\n      <td>River</td>\n      <td>4</td>\n      <td>4 PM - 9 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>41</th>\n      <td>Dorado</td>\n      <td>15000</td>\n      <td>River</td>\n      <td>5</td>\n      <td>4 AM - 9 PM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>42</th>\n      <td>Gar</td>\n      <td>6000</td>\n      <td>Pond</td>\n      <td>6</td>\n      <td>4 PM - 9 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>43</th>\n      <td>Arapaima</td>\n      <td>10000</td>\n      <td>River</td>\n      <td>6</td>\n      <td>4 PM - 9 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>44</th>\n      <td>Saddled Bichir</td>\n      <td>4000</td>\n      <td>River</td>\n      <td>4</td>\n      <td>9 PM - 4 AM</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n    </tr>\n    <tr>\n      <th>45</th>\n      <td>Sturgeon</td>\n      <td>10000</td>\n      <td>River (Mouth)</td>\n      <td>6</td>\n      <td>All day</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>46</th>\n      <td>Sea Butterfly</td>\n      <td>1000</td>\n      <td>Sea</td>\n      <td>1</td>\n      <td>All day</td>\n      <td>True</td>\n      <td>True</td>\n      <td>True</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>False</td>\n      <td>True</td>\n    </tr>\n    <tr>\n      <th>47</th>\n      <td>Sea Horse</td>\n      <td>1100</td>\n      <td>Sea</td>\n      <td>1</td>\n      <td>All day

You may have to strip unwanted newlines to clean up the table.

In [11]:
html_table.replace('\n', '')

'<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>Name</th>      <th>Price</th>      <th>Location</th>      <th>Shadow size</th>      <th>Time</th>      <th>Jan</th>      <th>Feb</th>      <th>Mar</th>      <th>Apr</th>      <th>May</th>      <th>Jun</th>      <th>Jul</th>      <th>Aug</th>      <th>Sep</th>      <th>Oct</th>      <th>Nov</th>      <th>Dec</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>Bitterling</td>      <td>900</td>      <td>River</td>      <td>1</td>      <td>All day</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>1</th>      <td>Pale Chub</td>      <td>200</td>      <td>River</td>      <td>1</td>      <td>9 AM - 4 PM</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>2</th>      <td>Crucian Carp</td>      <td>160</td>      <td>River</td>      <td>2</td>      <td>All day</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>3</th>      <td>Dace</td>      <td>240</td>      <td>River</td>      <td>3</td>      <td>4 PM - 9 AM</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>4</th>      <td>Carp</td>      <td>300</td>      <td>Pond</td>      <td>4</td>      <td>All day</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>5</th>      <td>Koi</td>      <td>4000</td>      <td>Pond</td>      <td>4</td>      <td>4 PM - 9 AM</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>6</th>      <td>Goldfish</td>      <td>1300</td>      <td>Pond</td>      <td>1</td>      <td>All day</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>7</th>      <td>Pop-Eyed Goldfish</td>      <td>1300</td>      <td>Pond</td>      <td>1</td>      <td>9 AM - 4 PM</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>8</th>      <td>Ranchu Goldfish</td>      <td>4500</td>      <td>Pond</td>      <td>2</td>      <td>9 AM - 4 PM</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>9</th>      <td>Killifish</td>      <td>300</td>      <td>Pond</td>      <td>1</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>10</th>      <td>Crawfish</td>      <td>200</td>      <td>Pond</td>      <td>2</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>11</th>      <td>Soft-Shelled Turtle</td>      <td>3750</td>      <td>River</td>      <td>4</td>      <td>4 PM - 9 AM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>12</th>      <td>Snapping Turtle</td>      <td>5000</td>      <td>River</td>      <td>5</td>      <td>9 PM - 4 AM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>13</th>      <td>Tadpole</td>      <td>100</td>      <td>Pond</td>      <td>1</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>14</th>      <td>Frog</td>      <td>120</td>      <td>Pond</td>      <td>2</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>15</th>      <td>Freshwater Goby</td>      <td>400</td>      <td>River</td>      <td>2</td>      <td>4 PM - 9 AM</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>16</th>      <td>Loach</td>      <td>400</td>      <td>River</td>      <td>2</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>17</th>      <td>Catfish</td>      <td>800</td>      <td>Pond</td>      <td>4</td>      <td>4 PM - 9 AM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>18</th>      <td>Giant Snakehead</td>      <td>5500</td>      <td>Pond</td>      <td>5</td>      <td>9 AM - 4 PM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>19</th>      <td>Bluegill</td>      <td>180</td>      <td>River</td>      <td>2</td>      <td>9 AM - 4 PM</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>20</th>      <td>Yellow Perch</td>      <td>300</td>      <td>River</td>      <td>3</td>      <td>All day</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>21</th>      <td>Black Bass</td>      <td>400</td>      <td>River</td>      <td>4</td>      <td>All day</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>22</th>      <td>Tilapia</td>      <td>800</td>      <td>River</td>      <td>3</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>23</th>      <td>Pike</td>      <td>1800</td>      <td>River</td>      <td>5</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>24</th>      <td>Pond Smelt</td>      <td>500</td>      <td>River</td>      <td>2</td>      <td>All day</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>    </tr>    <tr>      <th>25</th>      <td>Sweetfish</td>      <td>900</td>      <td>River</td>      <td>3</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>26</th>      <td>Cherry Salmon</td>      <td>1000</td>      <td>River (Clifftop)</td>      <td>3</td>      <td>4 PM - 9 AM</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>    </tr>    <tr>      <th>27</th>      <td>Char</td>      <td>3800</td>      <td>River (Clifftop) Pond</td>      <td>3</td>      <td>4 PM - 9 AM</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>    </tr>    <tr>      <th>28</th>      <td>Golden Trout</td>      <td>15000</td>      <td>River (Clifftop)</td>      <td>3</td>      <td>4 PM - 9 AM</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>    </tr>    <tr>      <th>29</th>      <td>Stringfish</td>      <td>15000</td>      <td>River (Clifftop)</td>      <td>5</td>      <td>4 PM - 9 AM</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>    </tr>    <tr>      <th>30</th>      <td>Salmon</td>      <td>700</td>      <td>River (Mouth)</td>      <td>4</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>31</th>      <td>King Salmon</td>      <td>1800</td>      <td>River (Mouth)</td>      <td>6</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>32</th>      <td>Mitten Crab</td>      <td>2000</td>      <td>River</td>      <td>2</td>      <td>4 PM - 9 AM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>    </tr>    <tr>      <th>33</th>      <td>Guppy</td>      <td>1300</td>      <td>River</td>      <td>1</td>      <td>9 AM - 4 PM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>    </tr>    <tr>      <th>34</th>      <td>Nibble Fish</td>      <td>1500</td>      <td>River</td>      <td>1</td>      <td>9 AM - 4 PM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>35</th>      <td>Angelfish</td>      <td>3000</td>      <td>River</td>      <td>2</td>      <td>4 PM - 9 AM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>36</th>      <td>Betta</td>      <td>2500</td>      <td>River</td>      <td>2</td>      <td>9 AM - 4 PM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>37</th>      <td>Neon Tetra</td>      <td>500</td>      <td>River</td>      <td>1</td>      <td>9 AM - 4 PM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>    </tr>    <tr>      <th>38</th>      <td>Rainbowfish</td>      <td>800</td>      <td>River</td>      <td>1</td>      <td>9 AM - 4 PM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>39</th>      <td>Piranha</td>      <td>2500</td>      <td>River</td>      <td>2</td>      <td>9 AM - 4 PM &amp; 9 PM - 4 AM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>40</th>      <td>Arowana</td>      <td>10000</td>      <td>River</td>      <td>4</td>      <td>4 PM - 9 AM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>41</th>      <td>Dorado</td>      <td>15000</td>      <td>River</td>      <td>5</td>      <td>4 AM - 9 PM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>42</th>      <td>Gar</td>      <td>6000</td>      <td>Pond</td>      <td>6</td>      <td>4 PM - 9 AM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>43</th>      <td>Arapaima</td>      <td>10000</td>      <td>River</td>      <td>6</td>      <td>4 PM - 9 AM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>44</th>      <td>Saddled Bichir</td>      <td>4000</td>      <td>River</td>      <td>4</td>      <td>9 PM - 4 AM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>45</th>      <td>Sturgeon</td>      <td>10000</td>      <td>River (Mouth)</td>      <td>6</td>      <td>All day</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>    </tr>    <tr>      <th>46</th>      <td>Sea Butterfly</td>      <td>1000</td>      <td>Sea</td>      <td>1</td>      <td>All day</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>    </tr>    <tr>      <th>47</th>      <td>Sea Horse</td>      <td>1100</td>      <td>Sea</td>      <td>1</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>    </tr>    <tr>      <th>48</th>      <td>Clown Fish</td>      <td>650</td>      <td>Sea</td>      <td>1</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>49</th>      <td>Surgeonfish</td>      <td>1000</td>      <td>Sea</td>      <td>2</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>50</th>      <td>Butterfly Fish</td>      <td>1000</td>      <td>Sea</td>      <td>2</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>51</th>      <td>Napoleonfish</td>      <td>10000</td>      <td>Sea</td>      <td>6</td>      <td>4 AM - 9 PM</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</td>      <td>True</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>False</td>    </tr>    <tr>      <th>52</th>      <td>Zebra Turkeyfish</td>      <td>500</td>      <td>Sea</td>      <td>3</td>      <td>All day</td>      <td>False</td>      <td>False</td>      <td>False</td>      <td>True</t

You can also save the table directly to a file.

In [12]:
df.to_html('fish_data.html')

In [13]:
# OSX Users can run this to open the file in a browser, 
# or you can manually find the file and open it in the browser
!open table.html

The file /Users/jeremybrent/Documents/Rutgers/Projects/etl_project/table.html does not exist.