### Create Dependencies

In [1]:
import pandas as pd
from sqlalchemy import create_engine
from config import username, password

### Extract CSV into DataFrame

In [2]:
villagers_file = "../Resources/villagers.csv"
villagers_df = pd.read_csv(villagers_file)
villagers_df["id"] = villagers_df["id"].astype("str")
villagers_df.head()

,row_n,id,name,gender,species,birthday,personality,song,phrase,full_id,url
0,2,admiral,Admiral,male,bird,1-27,cranky,Steep Hill,aye aye,villager-admiral,https://villagerdb.com/images/villagers/thumb/...
1,3,agent-s,Agent S,female,squirrel,7-2,peppy,DJ K.K.,sidekick,villager-agent-s,https://villagerdb.com/images/villagers/thumb/...
2,4,agnes,Agnes,female,pig,4-21,uchi,K.K. House,snuffle,villager-agnes,https://villagerdb.com/images/villagers/thumb/...
3,6,al,Al,male,gorilla,10-18,lazy,Steep Hill,Ayyeeee,villager-al,https://villagerdb.com/images/villagers/thumb/...
4,7,alfonso,Alfonso,male,alligator,6-9,lazy,Forest Life,it'sa me,villager-alfonso,https://villagerdb.com/images/villagers/thumb/...

### Eliminate columns unneeded for database.

In [3]:
villagers_cols = {"id","name","gender","species"}
villagers_transformed_df = villagers_df[villagers_cols].copy()
villagers_transformed_df['type'] = 'Villager'
villagers_transformed_df = villagers_transformed_df[['id','name','type','gender','species']]

# Setting index to the id
villagers_transformed_df = villagers_transformed_df.set_index("id")

villagers_transformed_df.head()

            name      type  gender    species
id
admiral  Admiral  Villager    male       bird
agent-s  Agent S  Villager  female   squirrel
agnes      Agnes  Villager  female        pig
al            Al  Villager    male    gorilla
alfonso  Alfonso  Villager    male  alligator

In [4]:
list(villagers_transformed_df.index.unique())

['admiral',
 'agent-s',
 'agnes',
 'al',
 'alfonso',
 'alice',
 'alli',
 'amelia',
 'anabelle',
 'anchovy',
 'angus',
 'anicotti',
 'ankha',
 'annalisa',
 'annalise',
 'antonio',
 'apollo',
 'apple',
 'astrid',
 'audie',
 'aurora',
 'ava',
 'avery',
 'axel',
 'baabara',
 'bam',
 'bangle',
 'barold',
 'bea',
 'beardo',
 'beau',
 'becky',
 'bella',
 'benedict',
 'benjamin',
 'bertha',
 'bettina',
 'bianca',
 'biff',
 'big-top',
 'bill',
 'billy',
 'biskit',
 'bitty',
 'blaire',
 'blanche',
 'bluebear',
 'bob',
 'bonbon',
 'bones',
 'boomer',
 'boone',
 'boots',
 'boris',
 'boyd',
 'bree',
 'broccolo',
 'broffina',
 'bruce',
 'bubbles',
 'buck',
 'bud',
 'bunnie',
 'butch',
 'buzz',
 'cally',
 'camofrog',
 'canberra',
 'candi',
 'carmen2',
 'caroline',
 'carrie',
 'cashmere',
 'celia',
 'cesar',
 'chadder',
 'charlise',
 'cheri',
 'cherry',
 'chester',
 'chevre',
 'chief',
 'chops',
 'chow',
 'chrissy',
 'claude',
 'claudia',
 'clay',
 'cleo',
 'clyde',
 'coach',
 'cobb',
 'coco',
 'cole',
 'colton',
 'cookie',
 'cousteau',
 'cranston',
 'croque',
 'cube',
 'curlos',
 'curly',
 'curt',
 'cyd',
 'cyrano',
 'daisy',
 'deena',
 'deirdre',
 'del',
 'deli',
 'derwin',
 'diana',
 'diva',
 'dizzy',
 'dobie',
 'doc',
 'dom',
 'dora',
 'dotty',
 'drago',
 'drake',
 'drift',
 'ed',
 'egbert',
 'elise',
 'ellie',
 'elmer',
 'eloise',
 'elvis',
 'erik',
 'eugene',
 'eunice',
 'fang',
 'fauna',
 'felicity',
 'filbert',
 'flip',
 'flo',
 'flora',
 'flurry',
 'francine',
 'frank',
 'freckles',
 'freya',
 'friga',
 'frita',
 'frobert',
 'fuchsia',
 'gabi',
 'gala',
 'gaston',
 'gayle',
 'genji',
 'gigi',
 'gladys',
 'gloria',
 'goldie',
 'gonzo',
 'goose',
 'graham',
 'greta',
 'grizzly',
 'groucho',
 'gruff',
 'gwen',
 'hamlet',
 'hamphrey',
 'hans',
 'harry',
 'hazel2',
 'henry',
 'hippeux',
 'hopkins',
 'hopper',
 'hornsby',
 'huck',
 'hugh',
 'iggly',
 'ike',
 'jacob',
 'jacques',
 'jambette',
 'jay',
 'jeremiah',
 'jitters',
 'joey',
 'judy',
 'julia',
 'julian',
 'june',
 'kabuki',
 'katt',
 'keaton',
 'ken',
 'ketchup',
 'kevin',
 'kid-cat',
 'kidd',
 'kiki',
 'kitt',
 'kitty',
 'klaus',
 'knox',
 'kody',
 'kyle',
 'leonardo',
 'leopold',
 'lily',
 'limberg',
 'lionel',
 'lobo',
 'lolly',
 'lopez',
 'louie',
 'lucha',
 'lucky',
 'lucy',
 'lyman',
 'mac',
 'maddie',
 'maelle',
 'maggie',
 'mallary',
 'maple',
 'marcel',
 'marcie',
 'margie',
 'marina',
 'marshal',
 'mathilda',
 'megan',
 'melba',
 'merengue',
 'merry',
 'midge',
 'mint',
 'mira',
 'miranda',
 'mitzi',
 'moe',
 'molly',
 'monique',
 'monty',
 'moose',
 'mott',
 'muffy',
 'murphy',
 'nan',
 'nana',
 'naomi',
 'nate',
 'nibbles',
 'norma',
 'octavian',
 'ohare',
 'olaf',
 'olive',
 'olivia',
 'opal',
 'ozzie',
 'pancetti',
 'pango',
 'paolo',
 'papi',
 'pashmina',
 'pate',
 'patty',
 'paula',
 'peaches',
 'peanut',
 'pecan',
 'peck',
 'peewee',
 'peggy',
 'pekoe',
 'penelope',
 'phil',
 'phoebe',
 'pierce',
 'pietro',
 'pinky',
 'piper',
 'pippy',
 'plucky',
 'pompom',
 'poncho',
 'poppy',
 'portia',
 'prince',
 'puck',
 'puddles',
 'pudge',
 'punchy',
 'purrl',
 'queenie',
 'quillson',
 'raddle',
 'rasher',
 'raymond',
 'renee',
 'reneigh',
 'rex',
 'rhonda',
 'ribbot',
 'ricky',
 'rizzo',
 'roald',
 'robin',
 'rocco',
 'rocket',
 'rod',
 'rodeo',
 'rodney',
 'rolf',
 'rooney',
 'rory',
 'roscoe',
 'rosie',
 'rowan',
 'ruby',
 'rudy',
 'sally2',
 'samson',
 'sandy',
 'savannah',
 'scoot',
 'shari',
 'sheldon',
 'shep',
 'sherb',
 'simon',
 'skye',
 'sly',
 'snake',
 'snooty',
 'soleil',
 'sparro',
 'spike',
 'spork',
 'sprinkle',
 'sprocket',
 'static',
 'stella',
 'sterling',
 'stinky',
 'stitches',
 'stu',
 'sydney',
 'sylvana',
 'sylvia',
 't-bone',
 'tabby',
 'tad',
 'tammi',
 'tammy',
 'tangy',
 'tank',
 'tasha',
 'teddy',
 'tex',
 'tia',
 'tiffany',
 'timbra',
 'tipper',
 'tom',
 'truffles',
 'tucker',
 'tutu',
 'twiggy',
 'tybalt',
 'ursala',
 'velma',
 'vesta',
 'vic',
 'victoria',
 'violet',
 'vivian',
 'vladimir',
 'wade',
 'walker',
 'walt',
 'wart-jr',
 'weber',
 'wendy',
 'whitney',
 'willow',
 'winnie',
 'wolfgang',
 'yuka',
 'zell',
 'zucker']

### Create database connection

In [5]:
connection_string = f"{username}:{password}@localhost:5432/ACNH_Critterpedia"
engine = create_engine(f'postgresql://{connection_string}')

In [6]:
# Confirm tables
engine.table_names()

['time', 'encyclopedia', 'months', 'collection', 'times']

### Load DataFrame into database

In [7]:
villagers_transformed_df.to_sql(name='encyclopedia', con=engine, if_exists='append', index=True)